# 운영 환경 설정
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DBNAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

toss:
  base-url: ${TOSS_BASE_URL}
  secret-key: ${TOSS_SECRET_KEY}

ncp:
  object-storage:
    endpoint: https://kr.object.ncloudstorage.com
    region: kr-standard
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    bucket: ${NCP_BUCKET:flash-deal-images}
    default-image-url: ${NCP_DEFAULT_IMAGE_URL}

scheduling:
  enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true